---
deployment:
  tasks:
    - export DEPLOYPATH=/home/themzjgb/public_html/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/..../js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/..../css